### ISSUE TITLE
TypeError: 'Element' object is not subscriptable

### ISSUE THREAD

**Issue by zzhuncle** [LinkedAi/flip#46]
I have downloaded the dataset, then run the codes, but it can not work, and assert error that "TypeError: 'Element' object is not subscriptable", can anyone help me? thanks very much!

**Comment by divait** [comment]
Hi @zzhuncle, 

It seem an error we solve 4 days ago but just today I'm deploying the new version with the fix, please be sure that you are using the new version 0.2.1.

If the error persist please let me know.

Thanks for the report!

**Comment by divait** [comment]
I'm closing  this thread because no interaction for a while.
